// src/pages/Index.vue
<template>
  <ul class="index">
    <li>
      <router-link to="/basic-geometries">Basic Geometries</router-link>
    </li>
  </ul>
</template>

<script lang="ts">
  import { defineComponent } from 'vue'

  export default defineComponent({})
</script>

<style scoped>
  .index {
    margin: 2rem;
  }
</style>

// src/pages/index.tsx
import React from 'react'
import { Link } from 'react-router-dom'

export default function Index() {
  return (
    <ul style={{ margin: '2rem' }}>
      <li><Link to="/basic-geometries">Basic Geometries</Link></li>
      <li><Link to="/suzanne">Suzanne</Link></li>
      <li><Link to="/clock">Clock</Link></li>
    </ul>
  )
}
